#import "../../../lib/lib.typ": *
#import "../../../lib/setup_cheatsheet.typ": cheatsheet-setup
#show: frame-style(styles.boxy)

#show: cheatsheet-setup(
  title: "Group Theory Cheatsheet",
  author: "Denis Titov",
  language: "GER",
)

= Finite Groups
#section[Groups][
  - *Group* $(G, *)$: set with a binary operation $G times G -> G$, $(g, h) |-> g h$.
    - *Associativity*: $(g h) k = g (h k)$.
    - *Identity element*: $exists bb(1): bb(1) g = g bb(1) = g$.
    - *Inverse*: $forall g in G, hsmall exists g^(-1): g g^(-1) = g^(-1) g = bb(1)$.
    - *Abelian*: $g h = h g$ (commutative).
]

#section[Products and Subgroups][
  - *Direct Product*: $circ = circ_(G cross H): (g, h) circ (g', h') = (g dot g', h dot h')$.

  - *Semidirect Product*: $G times.r_phi H$ with $rho: H -> "Aut"(G)$,
    $(g, h) circ (g', h') = (g dot rho(h)(g'), h dot h')$.

  - *Normal Subgroup*: $N "normalteiler" G$ iff $forall n in N, g in G: g n g^(-1) in N$.

  - *Examples*:
    $
      "Center": Z(G) = {z in G | forall g in G: z g = g z} "normalteiler" G\

      "Commutator Subgroup": [G, G] = "generated by" {g h g^(-1) h^(-1) | g, h in G} "normalteiler" G\
    $

  - *Subgroup*: $H subset G != emptyset$ iff $h_1, h_2 in H => h_1 h_2^(-1) in H$.

  - *Finding Subgroups*: Lagrange Theorem $abs(H) "divides" abs(G)$, check element orders, check kernels of homomorphisms.

    For $n, m = abs(G) => forall n : exists H subset G: abs(H) = m "if" m "teiler" n$
]

#section[Group Actions: Orbits and Stabilizers][
  - *Stabilizer*: $Stab(x) = {g in G | g x = x}$ (elements fixing $x$).

  - *Orbit*: $"Orb"(x) = {g x | g in G}$ (all images of $x$ under $G$).

  - *Center*: $Z(G) = {z in G | forall g in G: z g = g z}$.
]

#section[Orbit-Stabilizer and Quotients][
  - *Orbit-Stabilizer Theorem*: $|G| = |"Orb"(x)| dot |Stab(x)|$.

  For a group action of $G$ on a set $X$:
  - *Orbit* of $x$: $G x = "Orb"(x) = {g dot x | g in G} subset.eq X$.
  - *Stabilizer* of $x$: $Stab_G(x) = {g in G | g dot x = x} subset.eq G$.
  - *Fixed point set* of $g$: $Fix_X(g) = {x in X | g dot x = x} subset.eq X$.
  - *Orbit space*: $X\/G = { "Orb"(x) | x in X }$.
]

#section[Fixed Point Lemma][
  $|X\/G| = 1/abs(G) sum_(g in G) abs(Fix_X(g))$.

  $sum_(g in G) abs(Fix_X(g)) = sum_(x in X) abs(Stab(x))$.

  Stabilizer sizes are constant on orbits: $x, y$ in the same orbit 
  
  $=> abs(Stab(x)) = abs(Stab(y))$.

  If $Stab(x) = {1} forall x$: $abs(X\/G) = abs(X)/abs(G)$.

  Let $S = {(g, x) in G cross X: g dot x = x}$, 
  
  then $abs(S) = sum_g abs(Fix_X(g)) = sum_x abs(Stab(x))$.

  If $V = CC^X$ (functions on a finite set) with the permutation action, then
  $chi(g) = tr(rho(g)) = abs(Fix_X(g))$.

  Orbits partition $X$: $X = union.sq_(O in X\/G) O$.
]


#section[Group Homomorphsm][
  - *Homomorphism*: $phi: G -> H$ with $phi(g_1 g_2) = phi(g_1) phi(g_2)$.

  - *Implications*:
    $
      phi(id_G) = id_H hspace phi(g^m1) = phi(g)^m1 hspace phi(g^n) = phi(g)^n\
      ker(phi) = {g in G | phi(g) = id_H} "normalteiler" G\
      im(phi) = {h in H | exists g in G: phi(g) = h} "subgroup of" H\
      G\/ker(phi) iso im(phi) 
    $

  - *Beispiel*: $det(A B) = det(A) det(B)$
]

#section[Representations][
  - *Representation*: $rho: G -> GL(V)$ is Homomorphism, $V$ Vectorspace.

  - *Checklist*:
    $
      forall g in G, rho(g) in GL(V) "invertible, linear"\
      forall g, h in G, rho(g h) = rho(g) rho(h)\
    $

  - *Implications*:
    $rho(g h) = rho(g) rho(h) hspace rho(id_G) = id_V hspace rho(g^m1) = rho(g)^m1$

    - *Invariant Subspace*: $W subset V: rho(g) W subset W hsmall forall g in G$

    - *Irreducible*: no invariant subspaces other than ${0}$ and $V$

    - *Equivalent*: $rho_1 iso rho_2$ if $exists T: V_1 -> V_2$ 
    
    - *invertible*: with $T rho_1(g) = rho_2(g) T forall g in G$

    - *Character*: $chi_rho(g) = tr(rho(g))$ constant on conjugacy classes

  - *Schur*: Commuting Operator $=>$ Blockdiagonal.

  - *Fixpoint = Spur*: If $V = CC^X$, then $chi(g) = abs(Fix(g))$.
]

#section[Gruppe: $S_n$][
  Permutation von $n$ Elementen. Die Ordnung von $S_n$ ist $n!$. Für jede partition von $n$ gibt es eine irrep. Die Konjugationsklassen entsprechen den Zykelstrukturen der Permutationen. $abs(S_n) = n!$

  #grid(
    columns: 2,
    column-gutter: 1em,
    row-gutter: 0.5em,
    character_table(
      ($e$, $(1 2)$),
      ($chi_"triv"$, $chi_"sgn"$),
      (1, 1, 1, -1),
      group: $S_2$,
      class_sizes: (1, 1)
    ),

    character_table(
      ($e$, $(1 2)$, $(1 2 3)$),
      ($chi_"triv"$, $chi_"sgn"$, $chi_"2d"$),
      (1, 1, 1, 1, $-1$, 1, 2, 0, $-1$),
      group: $S_3$,
      class_sizes: (1, 3, 2)
    ),

    character_table(
      ($e$, $(1 2)$, $(1 2)\ (3 4)$, $( 1 2 3)$, $(1 2 3 4)$),
      ($chi^(4)_"triv"$, $chi^(1^4)_"sgn"$, $chi^(2,2)_"2d"$, $chi^(3,1)_"3d"$, $chi^(2,1,1)_"3d"$),
      (1,1,1,1,1,1, $-1$,1,1,$-1$,2,0,2,$-1$,0,3,1,$-1$,0,$-1$,3,$-1$,$-1$,0,1),
      group: $S_4$,
      class_sizes: (1,6,3,8,6)
    ),
     [
      \
      *Young Tableau*: Für Partitionen von $n$ in $k$ Teile ist die Dimension der irrep
      gegeben durch $dim = n!/(Pi_{"boxes"} "hook"("box"))$. Die Hook Length ist
      die Anzahl der Boxen rechts und unter der Box + 1. Zum Beispiel für $n = 7$
      und Partition $(4,2,1)$:
    ]

  )

  #grid(
    columns: 2,
    column-gutter: 1em,
    young_tableau(
      (4,2,1),
      (6, 4, 2, 1, 3, 1, 1)
    ),
    $
      => "dim" = (7 dot 6 dot 5 dot 4 dot 3 dot 2 dot 1)/(6 dot 4 dot 2 dot 1 dot 3 dot 1 dot 1) = 35\
    $
  )
]

#section[Group: $A_n$][
  Alternierende Gruppe: gerade Permutationen in $S_n$. Ordnung: $abs(A_n) = n!\/2$.

  #grid(
    columns: 2,
    column-gutter: 1em,
    row-gutter: 0.5em,
    character_table(
      ($e$, $(1 2)\ (34)$, $(1 2 3)$, $(1 3 2)$),
      ($chi_1$, $chi_1'$, $chi_1''$, $chi_3$),
      (1,1,1,1,1,1,$omega$, $omega^2$, 1,1,$omega^2$, $omega$, 3, -1, 0, 0),
      group: $abs(A_4)=12$,
      class_sizes: (1, 3, 4, 4)
    ),
    character_table(
      ($e$, $(1 2)\ (3 4)$, $(1 2 3)$, $(1 2 3 4 5)$, $(1 3 5 2 4)$),
      ($chi_1$, $chi_3$, $chi_3'$, $chi_4$, $chi_5$),
      (1, 1, 1, 1, 1, 3, $-1$, 0, $(1 + sqrt(5))/2$, $(1 - sqrt(5))/2$, 3, -1, 0, $(1 - sqrt(5))/2$, $(1 + sqrt(5))/2$, 4, 0, 1, -1, -1, 5, 1, -1, 0, 0),
      group: $A_5$,
      class_sizes: (1, 15, 20, 12, 12)
    ),
  )
]


#section[Gruppe: $D_n$][
  $
    D_2 = {1, R, S, R S} "mit" S R S = R, "abelbsch", D_2 iso ZZ_2 cross ZZ_2\
    D_n = {R^k, R^k S | k = 0, ..., n-1} = {1, R, R^2, ..., R^(n-1), S, R S, ..., R^(n-1) S}\
    R: "Rotation" 2 pi\/n, S: "Spiegelung" hspace abs(D_n) = 2 n\
  $
  

  #grid(
    columns: 2,
    column-gutter: 1em,
    row-gutter: 0.5em,
    character_table(
      ($e$, $R$, $S$, $R S$),
      ($chi_"triv"$, $chi_"sgnR"$, $chi_"sgnS"$, $chi_"sgnRS"$),
      (1,1,1,1,1,1,$-1$,$-1$,1,$-1$,1,$-1$,1,$-1$,$-1$,1),
      group: $|D_2| = 4$,
      class_sizes: (1,1,1,1)
    ),
    character_table(
      (1, $R, R^2$, $S, R S, R^2 S$),
      ($chi_"triv"$, $chi_"sgn"$, $chi_"2d"$),
      (1, 1, 1, 1, 1, $-1$, 2, $-1$, 0),
      group: $|D_3| = 6$,
    ), 
    character_table(
      (1, $R^2$, $R, R^3$, $S, R^2 S$, $R S , R^3 S$),
      ($chi_A_1$, $chi_A_2$, $chi_B_1$, $chi_B_2$, $chi_E^"2d"$),
      (1, 1, 1, 1, 1, 1, 1, 1, $-1$, $-1$, 1, 1, $-1$, 1, $-1$, 1, 1, $-1$, $-1$, 1, 2, $-2$, 0, 0, 0),
      group: $|D_4| = 8$
    ),

    [
      \
      *Konjugacy Classes*: 
      For $n$ uneven: $1[e], 2[R], 2[R^2], ..., 2 [R^((n-1)/2)], n[S]$
      
      For $n$ even:
      
      $1[e], 1[R^(n/2)], 2[R], 2[R^2], ...,$ 
      $2[R^(n/2-1)],n/2[S], n/2[R S]$
    ]
  )
]

#section[Gruppe: $ZZ_n$][
  - *Definition*:
    $
      ZZ_n = ZZ\/n ZZ #hspace "addition modulo n" #hspace [0], [1], ..., [n-1]\
    $

  - *Eigenschaften*: Alle irreps sind eindimensional. Konjugationsklassen bestehen aus einzelnen Elementen. $abs(ZZ_n) = n$. Hat eine Gruppe ein Element der Ordnung $abs(G)$, dann ist sie zyklisch und isomorph zu $ZZ_n$.

  - *Wurzel*: $omega = exp((2 pi i)/n) #hspace omega^n = 1$.

    #grid(
      columns: 3,
      column-gutter: 1em,
      character_table(
        (0, 1, 2),
        ($chi_0$, $chi_1$, $chi_2$),
        (1, 1, 1, 1, $omega$, $omega^2$, 1, $omega^2$, $omega^4$),
        group: $ZZ_3$
      ),

      character_table(
        (0, 1, 2, 3),
        ($chi_0$, $chi_1$, $chi_2$, $chi_3$),
        (1, 1, 1, 1, 1, $omega$, $omega^2$, $omega^3$, 1, $omega^2$, $omega^4$, $omega^6$, 1, $omega^3$, $omega^6$, $omega^9$),
        group: $ZZ_4$
      ),

      [\ A direct product of cyclic groups is abelian and all its irreps are one-dimensional.]
    )
]





= Representations

#section[Representations][
  - *Definition*: A (group) representation (Darstellung) is a homomorphism
    $
      rho: G -> GL(V)
    $
  where $V$ is a vector space.

  - *Check*: $forall g in G: rho(g) in GL(V) "invertible",  "linear" hspace rho(g h)=rho(g) rho(h)$

  - *Implications*:$rho(g h)= rho(g) rho(h) hspace rho(id_G)=id_V hspace rho(g^m1)=rho(g)^m1$

  - *Invariant Subspace*: $W subset V: rho(g) W subset W forall g in G$
    Man kommt mit Gruppendarstellungen nicht aus dem Unterraum raus.

  - *Subrepresentation*:
    Darstellung auf invariantem Unterraum.
    *Jede irrep* ist eine Underdarstellung und hat einen assoziierten *invarianten Unterraum*.

  - *Irrep*: no invariant subspaces other than $\{0\}$ and $V$.

  - *Equivalent*:
    $rho_1 iso rho_2$ iff exists invertible $T:V_1 -> V_2$ with $T rho_1(g)=rho_2(g)T forall g in G.$

  - *Complete reducibility*:
    Jede Darstellung endlicher Gruppe ist vollständig reduzibel,
    d.h. sie zerfällt in direkte Summe von irreps.

  - *Unitary representation*:
    Darstellung auf einem unitären Vektorraum:
    $rho(g)^m1=rho(g)^*$ Dann vollständig reduzibel und $rho <-> W => W^perp "invariant"$

  - *Schurs Lemma* (complex, finite-dimensional irreps $(rho_1,V_1), (rho_2,V_2)$):
    - Every linear map $T:V_1 -> V_2$ with $T rho_1(g)=rho_2(g)T forall g in G$ is either the zero map or an isomorphism.
    - Every linear map $T:V -> V$ with $T rho(g)= rho(g)T forall g in G$ is a multiple of the identity: $T= lambda id$ for some $ lambda in CC$.

      Commuting Operator $=>$ Block Diagonal (Schur).

  - *Example: Abelian groups*
    Abelsch wenn $g h=h g forall g,h in G$. Alle irreps sind eindimensional.

  - *Fixed points = trace (permutation representation):*
    if $V=CC^X$, then
    $
      chi(g)=abs(Fix(g))
    $

  - *Regular representation*:
    $rho_"reg": G -> GL(CC^G)$ with $rho_"reg"(g) e_h = e_(g h)$.
]

#section[Maschkes Theorem (condition for full decomp into irreps)][
  Let $G$ be a finite group and $V$ a finite-dim vec-space over $K$, where $rho: G -> GL(V)$ is a rep. If the characteristic of $K$ does not divide $|G|$, then every invariant subspace $W subset V$ has an invariant complement $W'$ such that $V = W oadd W'$ and every vector can be written uniquely as $w + w'$. 
  
  For $CC$ or $RR$, $"char"(K) = 0$, so always holds. For $"char"(FF_p) = p$, not always.

  Also every finite-dim rep of a finite group over such a field is a direct sum of irreps.
]

#section[Character][
  $chi(rho) = tr(rho(g))$ konst auf Konjugationsklassen $chi_rho (g) =chi_rho (h g h^m1)$
  $
    rho iso rho' => chi_rho = chi_rho' hsmall chi_rho (id) = dim(V) hsmall chi_(rho oadd rho') = chi_rho + chi_rho' hsmall chi_(rho tensor rho') = chi_rho dot chi_rho' \
    chi_rho^* = overline(chi_rho) hspace chi_"reg" (g) = cases(abs(G) "if" g=1, 0 "else" )\
    rho bold("unitär") => chi_rho (g^m1) = overline(chi_rho (g)), hspace "ord"(g)= k => rho(g)^k = id\
    chi_rho (g) = dim rho "teiler" k => hspace abs(chi_rho (g)) <= dim(rho)\
    {g in G|_(chi_rho (g)) = m} "normalteiler" 
  $
]

#section[Scalar Product][
  $
    (chi_1, chi_2) = 1/abs(G) sum_g overline(chi_1 (g)) chi_2 (g) = 1/abs(G) sum_"konj" abs(c) overline(chi_1 (c)) chi_2 (c)\
    (chi_rho, chi_rho') = cases(1 "if" rho iso rho', 0 "else") hspace rho "irrep" => (chi_rho, chi_rho) = 1\
    (chi_rho, chi_rho_1) = "Multiplicity of " rho_1 "in" rho\
    (chi_rho, chi_rho) = sum ("Multiplicities of irreps in" rho)^2\
    rho "irrep" => abs(G) = sum_"irrep" (dim rho_i)^2 hspace chi_1, ..., chi_k "ONB in" CC^k
  $
]

#section[Character Table][
  $
    abs(G) = sum_"irrep" dim(rho_i)^2 hspace "Anzahl Konjugationsklassen = Anzahl irreps"\
    (chi_i, chi_j) = delta_(i j) hspace "Orthogonality of Rows"\
    chi_i in.not RR => exists chi_j: chi_j = overline(chi_i) hspace "komplexe Darstellungen treten paarweise auf"\
    "if" dim(rho_i) = 1 "then" forall rho_j "irrep" => rho_i tensor rho_j "another irrep" rho_k "with" chi_k = chi_i dot chi_j\
    g^k = id => chi_rho (g) = tr(rho(g)) = sum_(r=1)^(dim rho) lambda_r "with" lambda_r^k = 1 hspace chi_rho(g) <= dim(rho)\
  $

  - *Building Character Tables*:
    - List conjugacy classes.
    - Determine irreps and their dimensions (sum of squares = |G|).
    - Use orthogonality relations to fill in character values.
    - Verify completeness and consistency.
    - If character is complex, its complex conjugate is also an irrep.
    - If cycles of length $k$ ($g^k = id$) appear, then character values are sums of $k$-th roots of unity. Eigenvalues of $rho(g)$ are $k$-th roots of unity, so $chi_rho(g) = sum lambda_r$ with $lambda_r^k = 1$ and $abs(chi_rho(g)) <= dim(rho)$.

  - *Quickly Finding Irreps*:
    - Does it fix any axis/line (invariant subspace)? => 1D irrep.
    - Does it preserve a decomposition into two subspaces? => 2D irrep.
    - Combine characters by tensoring known irreps to find new ones (especially for 1D irreps).
]

#section[Tensoring Representations and Characters][
  $
    (rho_1 tensor rho_2)(g) = rho_1(g) tensor rho_2(g) hspace chi_(rho_1 tensor rho_2)(g) = chi_rho_1(g) dot chi_rho_2(g)\
    "if" rho_1, rho_2 "irreps" => rho_1 tensor rho_2 "not necessarily irrep"\
    "if" dim(rho_i) = 1 "then" forall rho_j "irrep" => rho_i tensor rho_j "another irrep" rho_k "with" chi_k = chi_i dot chi_j\
  $
]

#section[Dealing with Compound Groups][
  - *Direct Product*: $G = G_1 cross G_2$ => $rho = rho_1 tensor rho_2$ with $chi_rho(g_1, g_2) = chi_{rho_1}(g_1) dot chi_{rho_2}(g_2)$.

    Then $"Irr"(G_1 cross G_2) = {rho_1 tensor rho_2: rho_1 in "Irr"(G_1), rho_2 in "Irr"(G_2)}$

  - *Conjugacy Classes*: $(g_1, g_2)$ and $(h_1, h_2)$ are conjugate in $G_1 cross G_2$ iff $g_1$ and $h_1$ are conjugate in $G_1$ and $g_2$ and $h_2$ are conjugate in $G_2$.
]

#section[Isotypical Components and Canonical Decomposition][
  Let $K in CC^n$ be physical transform such that $K rho(g) = rho(g) K$ for all $g in G$. Then $CC^n = oadd_lambda V_lambda$ and $V_lambda = rho_i^(oadd m_lambda)$ is invariant under $rho$ and an Isotypical Component (all copies of one irrep type bundled). For each $lambda$ irrep type $rho_i$ there is a projector $p_lambda = (dim rho_i)/abs(G) sum_g overline(chi_i (g)) rho(g)$ projecting onto $V_lambda = p_lambda (V )$.
]

= Eigenwert mit Symmetrien

#section[Phsyical Setups][
  - Vectorspace $V = CC^n$ represents states: displacements, wavefunctions, etc
  - Group Action $rho: G -> GL(V)$ represents physical symmetries: rotations, reflections, translations
  - Operator $A: V -> V$ represents physical observable: Hamiltonian, Inertia Tensor, Stiffness Matrix, etc

  Symmetry Condition: $rho(g) A = A rho(g) forall g in G => A$ preserves symmetries of each irrep.

  Consequences: Schurs Lemma $=>$ if $V$ irreducible, then $A = lambda bb(1) =>$ 1 irrep = 1 eigenvalue (degeneracy 1).

  If $V = V_1 oadd V_2 oadd ... oadd V_k$ with $V_i$ irreducible, then $A$ has at most $k$ distinct eigenvalues.

  If some irrep $rho_i$ appears $m_i$ times in the decomposition of $V$, then each eigenvalue corresponding to this irrep has at least degeneracy $m_i$. 
]

#section[Recipe for Eigenvalue Problems with Symmetries][
  - Check overall symmetry decomposition of underlying object (e.g. molecule, platonic solid).
  - Determine which decomposition describes the modified object (e.g. with defects, external fields, etc).
  - Compute character of the representation on the modified object (usually fixpoint counting).
  - Decompose character into irreps to find multiplicities. $m_i = (chi_rho, chi_i)$.
  - Use multiplicities to determine eigenvalue degeneracies.
  - If you need actual eigenvectors, construct projectors onto isotypical components and solve smaller eigenvalue problems there. $p_i = (dim W_i)/abs(G) sum_g overline(chi_i (g)) rho(g)$.

  Always check if the question asks for proper or improper symmetries (i.e. $O(3)$ vs $SO(3)$).
]

#section[Marked Structures Recipe][
  - Identify ambient symmetry group $G$ of unmarked structure (eg $G^+ subset SO(3)$)
  - Determine symmetry group $H subset G$ of marked structure (usually via fixpoint counting). Unually reduce platonic to dihedral groups $D_n$ or dihedral to cyclic groups $ZZ_n$.
  - Compute stabilizers and orbits of representative features (vertex, edge, face).
    $
      H = Stab_G(x) = {g in G | g x = x} hspace
    $
    With Orbit-Stab trick: Compute orbit size by "how many distinc places can the marking be moved by symmetries?". Then:
    $
      abs("Orb"(x)) = abs(G)\/abs(Stab_G(x)) hspace => hspace abs(H) = abs(G)\/abs("Orb"(x))\
    $
]

#section[Unphysical Modes][
  For Eigenvalue problems we solve
  $
    V(y^* + x) approx V(y^*) + 1/2 x^TT H x hspace "for" y^* "equilibrium"\
  $
  This $H$ is usually out $A$. Then $ddot(x) = - A x => A x_0 = omega^2 x_0$.

  Unphysical modes correspond to eigenvalue 0 of $A$ (rigid body motions, gauge freedoms, etc). They dont change $V$ and thus dont have a rstoring force. Their number can be determined by symmetry analysis of $A$.

  For a System where translation and rotation are physically possible, there are always 6 unphysical modes in $RR^3$ (3 translations + 3 rotations) and 3 unphysical modes in $RR^2$ (2 translations + 1 rotation). If some symmetries are broken (e.g. fixed point, plane, axis), the number of unphysical modes is reduced accordingly.
]

#section[Traces of Common Orthogonal Matrices][
  - Identity: $tr(id_n) = n$
  - Minus Identity: $tr(-id_n) = -n$
  - Permutation Matrix: $tr(P) = $ number of fixed points of the permutation
  - O(2):
    - Rotation by $alpha$: $tr(R(alpha)) = 2 cos(alpha), hsmall 120 deg = 3/2 pi: -1, hsmall 90 deg = pi/2: 0, hsmall 180 deg = pi: -2, hsmall 0 deg = 0: 2$
    - Reflection across origin: $tr(S) = 0$
  - O(3):
    - Rotation by $alpha$ around axis: $tr(R(alpha)) = 1 + 2 cos(alpha) hsmall 120 deg = 3/2 pi: 0, hsmall 90 deg = pi/2: 1, hsmall 180 deg = pi: -1, hsmall 0 deg = 0: 3$
    - Reflection across plane in origin: $tr(S) = 1$
    - Invesion (x -> -x): $tr(-id_3) = -3$
]

= Platonic Solids

#section[Markings rule][
  $
    G subset O(3) hspace G^+ := G inter SO(3)\
    "If a feature" x "is marked, then" Stab(x) = {g in G | g x = x}\
    abs(G) = abs("Orb"(x)) dot abs(Stab(x))\
  $
  Oriented markings (arrow on face, directed edge) usually drop $D_n -> ZZ_n$.
]

#section[Tetrahedron][
  $G iso S_4, abs(G) = 24 hspace G^+ iso A_4, abs(G^+) = 12$ 
    
  (symmetry via vertex permutations).

  - *Proper*: $Stab_(G^+)("vertex/face") iso ZZ_3$, $Stab_(G^+)("edge") iso ZZ_2$.

  - *Chain*: $A_4 supset ZZ_3$, $ZZ_2 supset {1}$.

  - *Correspondence*: $e <-> id$, $(1 2 3) <-> 120 deg$ rot vertex-face, $(1 3 2) <-> 240 deg$ rot vertex-face, $(12)(34) <-> 180 deg$ rot edge.

  - *Improper*: $Stab_G("vertex/face") iso D_3$, $Stab_G("edge") iso D_2 iso ZZ_2 cross ZZ_2$.

  - *Chain*: $S_4 supset A_4, D_3, D_2 supset {1}$.

  - *Correspondence*: 
    $
      &(e) <-> id, hsmall &&(1 2) <-> "ref across edge",\
      &(1 2 3) <-> 120 deg "rot vertex-face", hsmall &&(1 2)(3 4) <-> 180 deg "rot edge",\ 
      &(1 2 3 4) <-> 90 deg "rot edges + ref", hsmall &&(1 3)(2 4) <-> "ref across face"\
    $
]

#section[Cube][
  $G iso S_4 cross ZZ_2, abs(G) = 48 hspace G^+ iso S_4, abs(G^+) = 24$. 
  
  $S_4$ is permutations of body diagonals.

  - *Proper*: $Stab_(G^+)("vertex") iso ZZ_3$, $Stab_(G^+)("face") iso ZZ_4$, $Stab_(G^+)("edge") iso ZZ_2$.

  - *Chain*: $S_4 supset ZZ_4, ZZ_3, ZZ_2 supset {1}$.


  - *Improper*: $Stab_G("vertex") iso D_3$, $Stab_G("face") iso D_4$, $Stab_G("edge") iso D_2$.

  - *Chain*: $S_4 cross ZZ_2 supset S_4 supset D_4, D_3, D_2 supset {1}$.

  - *Correspondence*: 
    $
      &(e, 1) <-> id, hsmall &&(e, -1) <-> "inversion"\
      &((1 2), 1) <-> 180 deg "rot edge", hsmall &&((1 2), -1) <-> "rot edge + inversion",\
      &((1 2 3), 1) <-> 120 deg "rot vertex",hsmall &&((1 2 3), -1) <-> "rot vertex + inversion",\
      &((1 2 3 4), 1) <-> 90 deg "rot face", hsmall &&((1 2 3 4), -1) <-> "rot face + inversion",\
      &((1 2)(3 4), 1) <-> 180 deg "rot face", hsmall &&((1 2)(3 4), -1) <-> "rot face + inversion"\
      &((1 2)), 1) <-> 180 deg "rot edge", hsmall &&((1 2), -1) <-> "rot edge + inversion"\
    $
]

#section[Dodeca / Icosa][
  - *Group*: $G iso A_5 cross ZZ_2, abs(G) = 120 hspace G^+ iso A_5, abs(G^+) = 60$.

  - *Proper*: $Stab_(G^+)("vertex") iso ZZ_5$, $Stab_(G^+)("face") iso ZZ_3$, $Stab_(G^+)("edge") iso ZZ_2$.

  - *Chain*: $A_5 supset ZZ_5, ZZ_3, ZZ_2 supset {1}$.

  - *Correspondence*:
    $
      &(e) <-> id,\
      & (1 2 3 4 5) <-> 72 deg "rot vertex", hsmall&& (1 3 5 2 4) <-> 144 deg "rot vertex",\
      & (1 2 3) <-> 120 deg "rot face", hsmall&& (1 2)(3 4) <-> 180 deg "rot edge"\
    $

  - *Improper*: $Stab_G("vertex") iso D_5$, $Stab_G("face") iso D_3$, $Stab_G("edge") iso D_2$.

  - *Chain*: $A_5 cross ZZ_2 supset A_5 supset D_5, D_3, D_2 supset {1}$.
]

= Lie Gruppen und Lie Algebren

#section[General Linear Group $GL(n,\RR)$][
  $GL(n, CC) hspace GL(n, K) = {A in Mat(n, K)|det A != 0}$

  $gl(n, K) = Mat(n, K) hspace $
  
  - *Basis:* $E_(i j), 1 "at" (i, j), "else" 0$

  - *Dim*: $dim gl(n, RR) = dim GL(n, RR) = n^2$
  
    $dim gl(n, CC) = dim GL(n, CC) = 2 n^2$
  
  $GL(n, RR)$ has 2 connected components: $det>0$ and $det<0$.
]

#section[Special Linear Group $SL(n,\RR)$][
  $SL(n, RR), SL(n, CC)$
  
  $SL(n, K) = {A in GL(n, K)|det A = 1}$

  $sl(n, K) = {X in gl(n, K)|tr(X) = 0}$

  - *Basis:* $E_(i j), i != j; H_k = E_(k k) - E_(k+1 k+1)$ for $k = 1, ..., n-1$

  $dim sl(n, RR) = n^2 - 1 = dim SL(n, RR) = n^2-1$

  $dim sl(n, CC) = dim SL(n, CC) = 2(n^2 - 1)$

  $SL(2, CC)$: Jordan-type $D mat(a, b; 0, a^m1) D^m1$ used for connectedness
]

#section[Orthogonal Group $O(n)$][
  $O(n) = {A in GL(n, RR)|A^T A = id}$
  
  $SO(n) = {A in O(n)|det A = 1}$

  $o(n) = so(n) = {X in gl(n, RR)|X^T + X = 0}$

  - *Basis:* $F_(i j) = E_(i j) - E_(j i), 1 <= i < j <= n$

  - *Dim*: $dim so(n) = dim o(n) = dim SO(n) = dim O(n) = (n(n-1))/2$

  Every $A in O(n)$ can be block-diagonalized $A = O D O^m1$ with $D$ being 2d rotation matrix or $plus.minus 1$.

  $O(n)$ has 2 connected components: $det>0$ and $det<0$.

  - *Rodrigues*: $R(hat(n), alpha) = I + sin(alpha) K + (1 - cos(alpha)) K^2 hspace "wobei" K = mat(0, -n_3, n_2; n_3, 0, -n_1; -n_2, n_1, 0)$
]

#section[Unitary Group $U(n)$][
  $U(n) = {A in GL(n, CC)|A^* A = id}$
  
  $SU(n) = {A in U(n)|det A = 1}$

  $u(n) = {X in gl(n, CC)|X^* + X = 0} hspace su(n) = {X in u(n)|tr(X) = 0}$

  - *Basis*: $i E_(k k), E_(i j) - E_(j i), i(E_(i j) + E_(j i))$ for $1 <= k <= n, 1 <= i < j <= n$

  - *Dim*: $dim u(n) = dim U(n) = n^2 hspace dim su(n) = dim SU(n) = n^2 - 1$

  Every $B in U(n)$ is unitary diagonalizable $B = U D U^*$ with $D = diag(lambda_1, ..., lambda_n), abs(lambda_i) = 1$.

  $su(2) = {X in Mat(2, CC)|X = mat(i a, b + i c; -b + i c, -i a), a, b, c in RR} iso RR^3$ 
  
  via $X |-> (a, b, c)$

  - *$SU(2)$ Standard Basis with Pauli Matrices:* $t_1 = i sigma_1 = mat(0, i; i, 0), t_2 = i sigma_2 = mat(0, 1; -1, 0), t_3 = i sigma_3 = mat(i, 0; 0, -i)$,
  Bracket: $[t_j, t_k] = - sum_(l=1)^3 2 epsilon_(j k l) t_l$.
]

#section[Symplectic Linear Group $Sp(2n,\RR)$][
  $Sp(2n, RR) = {A in GL(2n, RR)|A^T J A = J} hspace J = mat(0, id_n; -id_n, 0)$

  $sp(2n) = {X in gl(2n, RR)|X^T J + J X = 0} = {mat(A, B_1; B_2, -A^T)|B_i^T = B_i}$

  - *Basis:* $A$ is free block: $n^2$, symmetric $B_i$: $n(n+1)/2$ each 
  
  $=> dim Sp(2n) = dim sp(2n) = n(2n + 1)$
]

#section[Lorentz Group $O(1,3)$][
  $O(1, 3) = {Lambda in GL(4, RR)| Lambda^T eta Lambda = eta}$
  
  $SO^+ (1, 3) = {Lambda in O(1, 3)|det Lambda = 1, Lambda_00 >= 1}$

  $so(1, 3) = {X in Mat(4, RR)| X^T eta + eta X = 0}$

  Any element $A = R_1 L(chi) R_2, hsmall R_1, R_2 in SO(3), chi in RR$, where 
  
  $L(chi) = mat(cosh(chi), sinh(chi), 0, 0; sinh(chi), cosh(chi), 0, 0; 0, 0, 1, 0; 0, 0, 0, 1)$ in x, with $L(chi_1) L(chi_2) = L(chi_1 + chi_2)$
  Components: $O(1, 3)$ has 4 connected components:
  
  $det>0, Lambda_00>1; det>0, Lambda_00< -1; det<0, Lambda_00>1; det<0, Lambda_00< -1$.

  Orthochrone means $Lambda_00 >= 1$. $abs(Lambda_00) >= 1$ always. 
  
  Time reversal with $T = diag(-1, 1, 1, 1)$
]

#section[$SL(2, CC)$ and $SO^+(1,3)$][
  $SL(2, CC) = {A in GL(2, CC)|det A = 1}$
  
  $sl(2, CC) = {X in gl(2, CC)|tr(X) = 0}$

  Identifies Minkovski vectors with 2x2 matrices $hat(x)$: $X |-> A X A^*$, thus:
  $SL(2, CC)\/{plus.minus id} iso SO^+(1, 3)$
]

#section[Euclidean Group $IO(3)$][

  Transforms $x |-> R x + b$, with $R in O(3), b in RR^3 => M = mat(R, b; 0, 1)$

  $IO(3) = {mat(R, b; 0, 1)| R in O(3), b in RR^3} = {x |-> R x + b|A in O(3), b in RR^3}$

  $(A_1, b_1) (A_2, b_2) = (A_1 A_2, A_1 b_2 + b_1), IO(3) iso O(3) times.l RR^3$

  $io(3) = {mat(Omega, v; 0, 0)| Omega in o(3), v in RR^3}$
    
  - *Basis*: ${J_1, J_2, J_3, P_1, P_2, P_3}$ where $J_i$ are $so(3)$ generators and $P_i$ translations ($b$).
]

#section[Poincare Group $IO(1,3)$][
  $IO(1, 3) = {mat(Lambda, a; 0, 1)| Lambda in O(1, 3), a in RR^4}$
  
  $ = {x |-> Lambda x + a|Lambda in O(1, 3), a in RR^4}$

  $(Lambda_1, a_1) (Lambda_2, a_2) = (Lambda_1 Lambda_2, Lambda_1 a_2 + a_1)$
  $IO(1, 3) iso O(1, 3) times.l RR^4$

  $io(1, 3) = so(1, 3) times.l RR^4 = {mat(X, v; 0, 0)| X in so(1, 3), v in RR^4}$
]

#section[$H_0$ and Minkowski Space][
  $H_0 = {X in Mat_(2, 2) (CC)|X = X^*, tr(X) = 1}$
    $
      A in H_0 => A = mat(z, x + i y; x - i y, -z) hspace (x, y, z) in RR^3\
      det(A) = - (x^2 + y^2 + z^2)\
      "Thus" H_0 iso RR^3 "with metric" det(A - lambda id) = lambda^2 + (x^2 + y^2 + z^2)\
    $
]

#section[Isometry][
  Is a distance preserving map: $d(x, y) = d(f(x), f(y))$ of a metric space. Every isometry of Euclidean space is of the form $x |-> A x + b$ with $A in O(n), b in RR^n$. The set of all isometries forms the Euclidean Group $IO(n) = O(n) times.l RR^n$.
]

#section[Calculating Lie Algebra of a Lie Group][
  *IF* group is defined as matrices satisfying certain equations:
  + Take smooth curve $A(t)$ in group with $A(0) = id$
  + Plug in constraints on group matrices into $A(t)$
  + Differentiate equations at $t = 0$ to get constraints on $A dot(0)$
  + The set of all $X = A'(0)$ satisfying these constraints is the Lie Algebra

  Determinant: $dv(, t) det(A(t)) = det(A(t)) tr(A(t)^m1 A'(t))$

  *Adjoint Reps*: $Ad(g) = g X g^m1, hsmall ad(X) Y = dv(,t)|_0 exp(t X) Y exp(-t X)$

  $
    bold("Example:") SU(n) = {A in GL(n, CC)|A^* A = id, det A = 1}\
    A(0) = id, X = dv(, t)|_0 A(t) => hspace dv(, t)|_0 det(A(t)) = det(id) tr(id X) = tr(X) = 0\
    dv(, t)|_0 A(t)^* A(t) = A'(0) A^* + A A'(0)^*
    = id^* X + X^* id = X + X^* = 0 hspace \
    => su(n) = {X in gl(n, CC)|X^* + X = 0, tr(X) = 0}\
  $

  *IF* Group defined as $F(A) = 0$ of some map $F$:
  + $frak(g) = ker(dd(F))_I$ (compute the jacobian at $id$)

  *IF* Group defined via Exponential Map:
  + $frak(g) = <X | exp(t X_i) in G forall t in RR>$
]

#section[Lie Bracket][
  Commutatior: $[g, h] = g h g^m1 h^m1$. For Matrix Lie Groups: $[X, Y] = X Y - Y X$

  - *Properties*:
    - Bilinear: $[a X + b Y, Z] = a [X, Z] + b [Y, Z]$
    - Antisymmetric: $[X, Y] = - [Y, X]$
    - Jacobi Identity: $[X, [Y, Z]] + [Y, [Z, X]] + [Z, [X, Y]] = 0$
]

#section[Adjoint Representation][
  For Lie Group $G$: $Ad: G -> "Aut"(frak(g)), Ad(g) X = g X g^m1$

  For Lie Algebra $frak(g)$: $ad: frak(g) -> End(frak(g)), ad(X) Y = [X, Y]$

  - Aut is the group of automorphisms (invertible linear maps preserving the Lie Bracket) 
  
    $"Aut"(frak(g)) = {phi in GL(frak(g))|phi([X, Y]) = [phi(X), phi(Y)] forall X, Y in frak(g)}$

  - End is the set of all linear maps $End(frak(g)) = {phi: frak(g) -> frak(g)|phi "linear"}$

  - *Properties*:
    - $Ad(g_1 g_2) = Ad(g_1) circ Ad(g_2)$
    - $ad([X, Y]) = [ad(X), ad(Y)]$
    - $dv(, t)|_0 Ad(exp(t X)) = ad(X)$
]

= SU(2) and SO(3)

#section[SU(2) and SO(3)][
  $SU(2) = {A in GL(2, CC)|A^* A = id, det A = 1}$
  
  $SO(3) = {R in GL(3, RR)|R^T R = id, det R = 1}$

  $SU(2)$ is the double cover of $SO(3)$: $SU(2)\/{plus.minus id} iso SO(3)$

  Irreps of $SU(2)$ are labeled by $n in ZZ_0^+$ (highest weight), with dimension $n + 1$. 
  
  Irreps of $SO(3)$ are labeled by integer spin $l$, with dimension $2 l + 1$.
  We index the $SO(3)$ irreps by the same symbols $V_n$, but only even $n$ occur:
  $V_0, V_2, V_4, ...$ (with $dim V_(2l) = 2l + 1$).

  A rep $V_n$ of $SU(2)$ descends to a rep of $SO(3)$ iff $n$ is even (equivalently, iff $-id$ acts trivially).
  In that case, the descended $SO(3)$-irrep is denoted $V_n$ (so $SO(3)$ has irreps $V_(2l)$ corresponding to spin $l=n/2$).
]

#section[Lie Algebras su(2) and so(3)][
  $su(2) = {X in Mat(2, CC)|X^* + X = 0, tr(X) = 0}$
  
  $so(3) = {X in Mat(3, RR)|X^T + X = 0}$

  Both have dimension 3 and are isomorphic as Lie algebras. The isomorphism can be explicitly constructed by mapping the standard basis of $su(2)$ (the Pauli matrices) to the standard basis of $so(3)$ (the generators of rotations around x, y, z axes):

  $
  t_1 = i sigma_1 = mat(0, i; i, 0) <-> J_x = mat(0, 0, 0; 0, 0, -1; 0, 1, 0)\
  t_2 = i sigma_2 = mat(0, 1; -1, 0) <-> J_y = mat(0, 0, 1; 0, 0, 0; -1, 0, 0)\
  t_3 = i sigma_3 = mat(i, 0; 0, -i) <-> J_z = mat(0, -1, 0; 1, 0, 0; 0, 0, 0)\
  $
]

#section[Irreps of SU(2) and SO(3)][
  - *SU(2)*: Irreps $V_n$ labeled by $n = 0, 1, 2, ...$ with dim $n + 1$ (spin $n/2$). 
    
    The representation space can be realized as homogeneous polynomials of degree $n$ in two complex variables.

  - *SO(3)*: Irreps labeled by integer spin $l = 0, 1, 2, ...$ with dim $2 l + 1$.
    With the above convention, these are exactly $V_(2l)$ (so only even indices occur): $V_0, V_2, V_4, ...$.

    The representation space can be realized as spherical harmonics of degree $l$.

  - *Irrep Correspondence*: The irrep $V_n$ of $SU(2)$ descends to an irrep of $SO(3)$ iff $n$ is even.
    In that case it descends to the $SO(3)$ irrep $V_n$ (equivalently: spin $l = n/2$).

    A rep of $SU(2)$ factors to a rep of $SO(3)$ iff $-id$ acts trivially.
  
    In $V_n$, the central element $-id$ acts as multiplication by $(-1)^n$. Thus, for even $n$, $-id$ acts as identity, allowing the representation to descend to $SO(3)$.
 
 - *Character Formulas*:
    $
      "For" SU(2): chi_n(theta) = sin((n + 1) theta / 2) / sin(theta / 2) hspace
      "For" SO(3): chi_(2l)(theta) = sin((l + 1/2) theta) / sin(theta / 2)
    $

    Here $theta$ is the rotation angle in $SO(3)$. A lift to $SU(2)$ has eigenvalue-angles $\pm theta/2$.

- *Dimensions*:
  $
    dim V_n = n + 1 hspace "for" SU(2) hspace
    dim V_(2l) = 2 l + 1 hspace "for" SO(3)
  $

  This is why $SO(3)$ only has odd-dimensional irreps (1, 3, 5, ...).
]

#section[Schurs Lemma for Lie Algebra Representations][
  Let $rho: frak(g) -> gl(V)$ be an irreducible representation of a Lie algebra $frak(g)$ on a complex vector space $V$. If $T in End(V)$ commutes with all operators $rho(X)$ for $X in frak(g)$, i.e. $T rho(X) = rho(X) T$ for all $X in frak(g)$, then $T$ is a scalar multiple of the identity operator on $V$:
  
  $
    T = lambda id_V hspace "for some" lambda in CC\
  $
]

#section[Decompositions of SU(2) Representations][
  Any finite-dimensional representation of $SU(2)$ can be decomposed into a direct sum of irreducible representations. Let $V = CC^m$.
  
  $
    V iso oprod_(n in ZZ_0^+) m_n V_n hspace "with" m_n in ZZ_0^+\
  $
  
  Here, $m_n$ is the multiplicity of the irrep $V_n$ in the decomposition. Restrict $rho$ to the maximal torus $T = {diag(e^(i theta), e^(-i theta))|theta in RR}$, then calculate the character $chi(theta)$

  $
    chi(theta) = tr(rho(A)) = sum_(l=1)^(m-1) n_l tr(rho_l (A))\
    rho_l (A): (rho_l (A) f_n)(theta) = e^(i n theta) f_n(theta) hspace "for" f_n in V_n\
  $

  By comparing the character $chi(theta)$ with the characters of the irreps $V_n$, we can determine the multiplicities $m_n$ and thus the decomposition of $V$ into irreducible representations.
]

#section[Basis of $V_n$][
  $V_1 = "span"{x_1, x_2, x_3} hspace V_2 = "span"{r^2 Y_(2, -2), r^2 Y_(2, -1), r^2 Y_(2, 0), r^2 Y_(2, 1), r^2 Y_(2, 2)}$
]

= Tensor Products and Clebsch-Gordan

#section[Tensor Products of Representations][
  Let $rho_1, rho_2$ be finite-dimensional representations of a group $G$ on vector spaces $V_1, V_2$. The tensor product representation $rho_1 tensor rho_2$ is defined on the tensor product space $V_1 tensor V_2$ by:

  $
    (rho_1 tensor rho_2)(g) = rho_1(g) tensor rho_2(g) hspace "for all" g in G
  $

  - *Vectors*: 
  
    $
      (v_1 tensor v_2) |-> rho_1(g) v_1 tensor rho_2(g) v_2\
      (rho_1 tensor rho_2)(g)(v_1 tensor v_2) =  rho_1(g) v_1 tensor rho_2(g) v_2\
    $

  - *Lie Algrebras*:
  
    $
      (X_1 tensor X_2)(v_1 tensor v_2) = (X_1 v_1) tensor v_2 + v_1 tensor (X_2 v_2)\
    $
]

#section[Symmetrical and Antisymmetrical Tensor Products][
  Let $V^(tensor n) = V tensor V tensor ... tensor V$ ($n$ times), $dim V^(tensor n) = (dim V)^n$.

  $
    &S^n V = {v in V^(tensor n)|forall sigma in S_n: sigma v = v} hspace &&"Symmetric n-th Power"\
    &Lambda^n V = {v in V^(tensor n)|forall sigma in S_n: sigma v = sgn(sigma) v} hspace&& "Antisymmetric n-th Power"\
  $

  $
    dim S^n V = binom(dim V + n - 1, n) hspace dim Lambda^n V = binom(dim V, n) = d!/(n! (d - n)!)\
  $

  - *Decomposition*:
    $
      V_n tensor V_n = S^2 V_n oadd Lambda^2 V_n\
      S^2 V_n = V_(2 n) oadd V_(2 n - 4) oadd V_(2 n - 8) oadd ...\
      Lambda^2 V_n = V_(2 n - 2) oadd V_(2 n - 6) oadd V_(2 n - 10) oadd ...\
    $
]

#section[Clebsch-Gordan Formula][
  For $SU(2)$ irreps with dimension $dim V_n = n + 1$ and $dim V_m = m + 1$:

  $
    V_m tensor V_n iso V_(m + n) oadd V_(m + n - 2) oadd ... oadd V_(abs(m - n))\
  $

]
= Polynomials and Spherical Harmonics

#section[Homogeneous Polynomials][
  A polynomial $p(x_1, ..., x_n)$ is homogeneous of degree $d$ if all its monomials have total degree $d$:
  
  $
    H_l = {sum_(alpha in NN^3)^(abs(alpha) = l) c_alpha x^alpha | c_alpha in CC} hspace "with" x^alpha = x_1^(alpha_1) x_2^(alpha_2) ... x_n^(alpha_n)\
    dim(H_l) = 1/2 (l+1)(l+2) "for" n = 3\
  $

  - *Scalar Product*:
    $
      (f, g) = integral_(S^(n-1)) overline(f(x)) g(x) dd(Omega)\
    $

  $H_l$ carries a representation of $SO(n)$ via $(rho(R) f)(x) = f(R^m1 x)$ and is unitary with respect to the above scalar product. $Delta: H_l -> H_(l-2)$ commutes with this action.
]

#section[Harmonic Polynomials][
  Harmonic polynomials are homogeneous polynomials in $H_l$ that are annihilated by the Laplacian:
  
  
  $
    V_l = {p in H_l | Delta p = 0} hspace "with" Delta = sum_(i=1)^n d^2/(dx_i)^2\
    dim(V_l) = 2 l + 1 "for" n = 3
  $

  $V_l$ is an irreducible representation of $SO(3)$ called the space of spherical harmonics of degree $l$. The representation is given by $(rho(R) f)(x) = f(R^m1 x)$.
]

#section[Spherical Harmonics][
  The spherical harmonics $Y_l^m(theta, phi)$ form an orthonormal basis of $V_l$:
  
  $
    Y_l^m(theta, phi) = sqrt((2 l + 1)/(4 pi) (l - m)!/(l + m)!) P_l^m(cos theta) e^(i m phi) hspace "for" -l <= m <= l\
  $

  Here, $P_l^m$ are the associated Legendre polynomials. The spherical harmonics satisfy:
  
  $
    Delta_(S^2) Y_l^m = - l (l + 1) Y_l^m\
  $

  where $Delta_(S^2)$ is the Laplace-Beltrami operator on the sphere.

  - *Legendre Polynomials*:
    $
      &P_l (x) = 1/(2^l l!) d^l/(dx^l) (x^2 - 1)^l hspace &&"Legendre Polynomial"\
      &P_l^m (x) = (1 - x^2)^(m/2) d^m/(dx^m) P_l (x) hspace &&"Associated Legendre Polynomial"\
    $
]